# Multilayer Perceptron

In [31]:
import numpy as np

XOR

In [32]:
x1 = [0,0,1,1]
x2 = [0,1,0,1]
y = [0,1,1,0]

#As y changes values twice, we will need two lines to separate the 1's and the 0's

In [33]:
#Need to initialize a value for the first comparison
compare = y[0]

#This is the count of the number of lines necessary to solve the problem
count = 0

for element in y:
    if element != compare:
        count += 1
    compare = element

print(count)

2


In [34]:
#Initialize the values of w and b
w = []
b = 1

for x in range(0,count):
    w = np.append(w,1)


In [35]:
print(w)
print(b)

[1. 1.]
1


In [36]:
def activation(input):
    if input >=0:
        return 1
    else:
        return 0

In [37]:
#find initial values of z and yhat
yhat = np.zeros(np.size(x1))

for j in range (0, np.size(x1)):
    temp = []
    temp = np.append(temp,x1[j])
    temp = np.append(temp,x2[j])
    z = np.dot(temp,w)
    print(z)
    z = z + b
    print(z)
    yhat[x] = activation(x)

print(yhat)

0.0
1.0
1.0
2.0
1.0
2.0
2.0
3.0
[0. 1. 0. 0.]


In [38]:
#compare with actual values
error = y - yhat
print(y)
print(yhat)

print(error)

[0, 1, 1, 0]
[0. 1. 0. 0.]
[0. 0. 1. 0.]
